version: "3"
services:
  db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: appDB
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d:ro
            - db_volume:/var/lib/mysql
        ports:
            - "3308:3306"
  nginx:
        image: nginx
        restart: always
        volumes:
            - ./nginx/content:/etc/nginx/html/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "80:80"
        links:
            - db
#   parser:
#         build:
#             context: ./parser
#         image: news-maker
#         container_name: news-maker
#         restart: unless-stopped

#         command: ["python3", "main.py"]

volumes:
  db_volume:
