version: "3"
services:
    db:
        image: mysql
        container_name: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_USER: flask
            MYSQL_PASSWORD: example
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: appdb
            HOSTNAME: db
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d:ro
            - database_volume:/var/lib/mysql
        ports:
            - "3310:3306"
    flask:
        image: flask
        container_name: flask
        build:
            dockerfile: .docker/Dockerfile
            context: ./service/
        volumes:
            - ./:/usr/src/app/
        restart: unless-stopped
        environment:
            DB_HOST: db
            DB_NAME: appdb
            DB_USER: flask
            DB_PASSWORD: example
        ports:
            - 8080:5000
        links:
            - db
        depends_on:
            - db
        command: ["flask", "run", "--host", "0.0.0.0"]
    nginx:
        image: nginx
        container_name: nginx
        restart: always
        volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
        - "80:80"
        links:
        - db

volumes:
  database_volume:
